agents:
  - name: crewai-agent
    service: crewai-agent
    port: 8080
    description: "CrewAI research and analysis agent"
    resources:
      prod:
        cpu: "1"           
        memory: "512Mi"       
        min_instances: 0      
        max_instances: 1      
        concurrency: 80      

  - name: langraph-agent
    service: langraph-agent
    port: 8082
    description: "LangGraph decision-making and workflow agent"
    resources:
      prod:
        cpu: "1"
        memory: "512Mi"
        min_instances: 0
        max_instances: 1
        concurrency: 80

  - name: adk-agent
    service: adk-agent
    port: 8083
    description: "ADK data processing and analysis agent"
    resources:
      prod:
        cpu: "1"            
        memory: "1Gi"         
        min_instances: 0
        max_instances: 1      
        concurrency: 80      

global:
  timeout: 120              
  execution_environment: "gen2"  
  cpu_boost: true           

environments:
  prod:
    suffix: ""              
    cost_optimized: true

labels:
  managed-by: "github-actions"
  cost-optimized: "true"