name: Python Test Script

on:
  workflow_dispatch:

jobs:
  python-test:
    name: Test using Python script
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx asyncio
        
    - name: Create env file for agent
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > agents/crewai-agent/.env
        echo "GEMINI_MODEL=gemini-2.0-flash-exp" >> agents/crewai-agent/.env
        
    - name: Build and start crewai-agent
      run: |
        cd agents/crewai-agent
        docker build -t crewai-agent .
        docker run -d --name crewai-agent \
          --env-file .env \
          -p 8080:8080 \
          crewai-agent
        
    - name: Wait for agent to start
      run: |
        echo "Waiting for agent to start..."
        sleep 30
        
        # Check if container is running
        docker ps
        
        # Show logs
        echo "=== Agent logs ==="
        docker logs crewai-agent
        
    - name: Run Python test script
      run: |
        echo "Running test_crewai_agent.py..."
        python tests/test_crewai_agent.py
        
    - name: Cleanup
      if: always()
      run: |
        docker stop crewai-agent || true
        docker rm crewai-agent || true