name: Real API Test

on:
  workflow_dispatch:

jobs:
  real-api-test:
    name: Test with Real API
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check files exist
      run: |
        echo "Checking if agent files exist..."
        ls -la agents/crewai-agent/
        
    - name: Build crewai-agent
      run: |
        echo "Building crewai-agent..."
        cd agents/crewai-agent
        docker build -t test-gemini .
        echo "Build successful!"
        
    - name: Test with real API key
      run: |
        echo "Testing with real API key..."
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > test.env
        echo "GEMINI_MODEL=gemini-2.5-flash" >> test.env
        
        # Start container
        docker run -d --name test-container \
          --env-file test.env \
          -p 8080:8080 \
          test-gemini
        
        # Wait for startup
        sleep 30
        
        # Check logs
        echo "=== Container logs ==="
        docker logs test-container
        
        # Health check
        echo "=== Health check ==="
        curl -s http://localhost:8080/health | jq . || echo "Health check failed"
        
        # Capabilities check
        echo "=== Capabilities ==="
        curl -s http://localhost:8080/capabilities | jq . || echo "Capabilities failed"
        
        # Test actual task execution
        echo "=== Testing real task execution ==="
        curl -X POST http://localhost:8080/execute \
          -H "Content-Type: application/json" \
          -d '{
            "task_type": "research",
            "description": "Quick test of AI capabilities",
            "context": {"test": true}
          }' | jq . || echo "Task execution failed"
        
        # Cleanup
        docker stop test-container
        docker rm test-container