name: Simple Test

on:
  workflow_dispatch:

jobs:
  simple-test:
    name: Basic Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check files exist
      run: |
        echo "Checking if agent files exist..."
        ls -la agents/
        ls -la agents/crewai-agent/
        ls -la agents/langraph-agent/ 
        ls -la agents/adk-agent/
        
    - name: Test one Docker build
      run: |
        echo "Building one agent (crewai-agent)..."
        cd agents/crewai-agent
        docker build -t test-gemini .
        echo "Build successful!"
        
    - name: Test image runs
      run: |
        echo "Testing if image can start..."
        echo "GOOGLE_API_KEY=fake-key" > test.env
        echo "GEMINI_MODEL=gemini-2.0-flash-exp" >> test.env
        
        # Start container in background
        docker run -d --name test-container \
          --env-file test.env \
          -p 8080:8080 \
          test-gemini
        
        # Wait a bit
        sleep 20
        
        # Check if it's running
        docker ps
        
        # Try to get logs
        echo "Container logs:"
        docker logs test-container
        
        # Try health check
        echo "Testing health endpoint..."
        curl -v http://localhost:8080/health || echo "Health check failed"
        
        # Cleanup
        docker stop test-container
        docker rm test-container