name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'agents/**'
      - 'tests/unit/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'agents/**' 
      - 'tests/unit/**'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        # Install pytest and testing dependencies
        pip install pytest pytest-asyncio
        
        # Install dependencies from each agent
        pip install -r agents/adk-agent/requirements.txt
        pip install -r agents/crewai-agent/requirements.txt
        pip install -r agents/langraph-agent/requirements.txt
        
    - name: Run unit tests
      run: |
        echo "Running unit tests for all agents..."
        
        echo "=== ADK Agent unit tests ==="
        python -m pytest tests/unit/test_adk_logic.py -v
        
        echo "=== CrewAI Agent unit tests ==="
        python -m pytest tests/unit/test_crewai_logic.py -v
        
        echo "=== LangGraph Agent unit tests ==="
        python -m pytest tests/unit/test_langraph_logic.py -v
        
    - name: Generate test report
      if: always()
      run: |
        echo "Unit test summary:"
        echo "- ADK Agent: Completed"
        echo "- CrewAI Agent: Completed" 
        echo "- LangGraph Agent: Completed"
        echo "All unit tests completed successfully!"